import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

const SCHOOLS = [
  {
    number: 1,
    slug: "computer-science",
    title: "School of Computer Science",
    subtitle: "CS Fundamentals",
    description: "Master the foundations of computer science including mathematics, logic, digital electronics, and computer architecture.",
    icon: "cpu",
    color: "#00ff41",
    order: 1,
    categories: [
      { slug: "mathematics", title: "Mathematics", order: 1, modules: [
        { slug: "set-theory", title: "Set Theory", order: 1 },
        { slug: "logic", title: "Logic", order: 2 },
        { slug: "proof-techniques", title: "Proof Techniques", order: 3 },
        { slug: "discrete-mathematics", title: "Discrete Mathematics", order: 4 },
        { slug: "linear-algebra", title: "Linear Algebra", order: 5 },
        { slug: "calculus", title: "Calculus", order: 6 },
        { slug: "probability", title: "Probability & Statistics", order: 7 },
      ]},
      { slug: "digital-electronics", title: "Digital Electronics", order: 2, modules: [
        { slug: "boolean-algebra", title: "Boolean Algebra", order: 1 },
        { slug: "logic-gates", title: "Logic Gates", order: 2 },
        { slug: "combinational-circuits", title: "Combinational Circuits", order: 3 },
        { slug: "sequential-circuits", title: "Sequential Circuits", order: 4 },
        { slug: "memory-units", title: "Memory Units", order: 5 },
      ]},
      { slug: "computer-architecture", title: "Computer Architecture", order: 3, modules: [
        { slug: "cpu-architecture", title: "CPU Architecture", order: 1 },
        { slug: "instruction-set", title: "Instruction Set Architecture", order: 2 },
        { slug: "memory-hierarchy", title: "Memory Hierarchy", order: 3 },
        { slug: "pipelining", title: "Pipelining", order: 4 },
        { slug: "parallel-architectures", title: "Parallel Architectures", order: 5 },
      ]},
      { slug: "programming-fundamentals", title: "Programming Fundamentals", order: 4, modules: [
        { slug: "variables-types", title: "Variables & Data Types", order: 1 },
        { slug: "control-flow", title: "Control Flow", order: 2 },
        { slug: "functions", title: "Functions & Scope", order: 3 },
        { slug: "data-structures", title: "Data Structures", order: 4 },
        { slug: "algorithms", title: "Algorithms & Complexity", order: 5 },
        { slug: "oop", title: "Object-Oriented Programming", order: 6 },
        { slug: "functional-programming", title: "Functional Programming", order: 7 },
      ]},
    ],
  },
  {
    number: 2,
    slug: "programming-languages",
    title: "School of Programming Languages",
    subtitle: "50+ Languages",
    description: "Explore programming language theory, compilers, runtimes, and hands-on experience with 50+ programming languages.",
    icon: "code",
    color: "#00f0ff",
    order: 2,
    categories: [
      { slug: "language-paradigms", title: "Language Paradigms", order: 1, modules: [
        { slug: "imperative", title: "Imperative Programming", order: 1 },
        { slug: "declarative", title: "Declarative Programming", order: 2 },
        { slug: "object-oriented", title: "Object-Oriented", order: 3 },
        { slug: "functional", title: "Functional Programming", order: 4 },
        { slug: "logic-programming", title: "Logic Programming", order: 5 },
        { slug: "concurrent", title: "Concurrent Programming", order: 6 },
      ]},
      { slug: "compilers", title: "Compilers", order: 2, modules: [
        { slug: "lexical-analysis", title: "Lexical Analysis", order: 1 },
        { slug: "parsing", title: "Parsing & Syntax Analysis", order: 2 },
        { slug: "semantic-analysis", title: "Semantic Analysis", order: 3 },
        { slug: "code-generation", title: "Code Generation", order: 4 },
        { slug: "optimization", title: "Optimization", order: 5 },
      ]},
      { slug: "runtimes", title: "Runtimes & VMs", order: 3, modules: [
        { slug: "memory-management", title: "Memory Management", order: 1 },
        { slug: "garbage-collection", title: "Garbage Collection", order: 2 },
        { slug: "jit-compilation", title: "JIT Compilation", order: 3 },
        { slug: "virtual-machines", title: "Virtual Machines", order: 4 },
        { slug: "interpreters", title: "Interpreters", order: 5 },
      ]},
      { slug: "language-spotlights", title: "Language Spotlights", order: 4, modules: [
        { slug: "python", title: "Python", order: 1 },
        { slug: "javascript", title: "JavaScript", order: 2 },
        { slug: "typescript", title: "TypeScript", order: 3 },
        { slug: "rust", title: "Rust", order: 4 },
        { slug: "go", title: "Go", order: 5 },
        { slug: "java", title: "Java", order: 6 },
        { slug: "csharp", title: "C#", order: 7 },
        { slug: "cpp", title: "C++", order: 8 },
        { slug: "swift", title: "Swift", order: 9 },
        { slug: "kotlin", title: "Kotlin", order: 10 },
      ]},
    ],
  },
  {
    number: 3,
    slug: "web-development",
    title: "School of Web Development",
    subtitle: "Frontend & Backend",
    description: "Master modern web development from HTML and CSS to full-stack frameworks, APIs, and performance optimization.",
    icon: "globe",
    color: "#ffb000",
    order: 3,
    categories: [
      { slug: "html-css", title: "HTML & CSS", order: 1, modules: [
        { slug: "html-fundamentals", title: "HTML Fundamentals", order: 1 },
        { slug: "css-fundamentals", title: "CSS Fundamentals", order: 2 },
        { slug: "css-layout", title: "CSS Layout (Flexbox & Grid)", order: 3 },
        { slug: "responsive-design", title: "Responsive Design", order: 4 },
        { slug: "css-animations", title: "CSS Animations", order: 5 },
        { slug: "css-preprocessors", title: "CSS Preprocessors", order: 6 },
      ]},
      { slug: "javascript", title: "JavaScript", order: 2, modules: [
        { slug: "js-fundamentals", title: "JS Fundamentals", order: 1 },
        { slug: "dom-manipulation", title: "DOM Manipulation", order: 2 },
        { slug: "async-js", title: "Async JavaScript", order: 3 },
        { slug: "es6-plus", title: "ES6+ Features", order: 4 },
        { slug: "js-patterns", title: "JS Design Patterns", order: 5 },
        { slug: "testing", title: "Testing JavaScript", order: 6 },
      ]},
      { slug: "frontend-frameworks", title: "Frontend Frameworks", order: 3, modules: [
        { slug: "react", title: "React", order: 1 },
        { slug: "vue", title: "Vue.js", order: 2 },
        { slug: "angular", title: "Angular", order: 3 },
        { slug: "svelte", title: "Svelte", order: 4 },
        { slug: "nextjs", title: "Next.js", order: 5 },
        { slug: "state-management", title: "State Management", order: 6 },
      ]},
      { slug: "backend", title: "Backend Development", order: 4, modules: [
        { slug: "nodejs", title: "Node.js", order: 1 },
        { slug: "express", title: "Express.js", order: 2 },
        { slug: "api-design", title: "API Design (REST & GraphQL)", order: 3 },
        { slug: "authentication", title: "Authentication & Authorization", order: 4 },
        { slug: "web-security", title: "Web Security", order: 5 },
        { slug: "performance", title: "Web Performance", order: 6 },
      ]},
    ],
  },
  {
    number: 4,
    slug: "mobile-development",
    title: "School of Mobile Development",
    subtitle: "Android & iOS",
    description: "Build mobile applications for Android, iOS, and cross-platform using modern frameworks and tools.",
    icon: "smartphone",
    color: "#ff00aa",
    order: 4,
    categories: [
      { slug: "android", title: "Android Development", order: 1, modules: [
        { slug: "kotlin-basics", title: "Kotlin Basics", order: 1 },
        { slug: "android-fundamentals", title: "Android Fundamentals", order: 2 },
        { slug: "jetpack-compose", title: "Jetpack Compose", order: 3 },
        { slug: "android-architecture", title: "Android Architecture", order: 4 },
        { slug: "android-networking", title: "Networking & Data", order: 5 },
      ]},
      { slug: "ios", title: "iOS Development", order: 2, modules: [
        { slug: "swift-basics", title: "Swift Basics", order: 1 },
        { slug: "swiftui", title: "SwiftUI", order: 2 },
        { slug: "ios-fundamentals", title: "iOS Fundamentals", order: 3 },
        { slug: "ios-architecture", title: "iOS Architecture", order: 4 },
        { slug: "core-data", title: "Core Data & Networking", order: 5 },
      ]},
      { slug: "cross-platform", title: "Cross-Platform", order: 3, modules: [
        { slug: "react-native", title: "React Native", order: 1 },
        { slug: "flutter", title: "Flutter", order: 2 },
        { slug: "kotlin-multiplatform", title: "Kotlin Multiplatform", order: 3 },
        { slug: "xamarin", title: "Xamarin", order: 4 },
      ]},
    ],
  },
  {
    number: 5,
    slug: "desktop-development",
    title: "School of Desktop Development",
    subtitle: "Desktop Apps",
    description: "Create desktop applications using Electron, Tauri, Qt, .NET, and other frameworks.",
    icon: "monitor",
    color: "#00aaff",
    order: 5,
    categories: [
      { slug: "electron", title: "Electron", order: 1, modules: [
        { slug: "electron-basics", title: "Electron Fundamentals", order: 1 },
        { slug: "main-renderer", title: "Main & Renderer Process", order: 2 },
        { slug: "electron-apis", title: "Electron APIs", order: 3 },
        { slug: "packaging", title: "Packaging & Distribution", order: 4 },
      ]},
      { slug: "tauri", title: "Tauri", order: 2, modules: [
        { slug: "tauri-basics", title: "Tauri Fundamentals", order: 1 },
        { slug: "rust-backend", title: "Rust Backend", order: 2 },
        { slug: "tauri-apis", title: "Tauri APIs", order: 3 },
      ]},
      { slug: "native-desktop", title: "Native Desktop", order: 3, modules: [
        { slug: "qt", title: "Qt Framework", order: 1 },
        { slug: "dotnet", title: ".NET Desktop", order: 2 },
        { slug: "javafx", title: "JavaFX", order: 3 },
        { slug: "gtk", title: "GTK", order: 4 },
      ]},
    ],
  },
  {
    number: 6,
    slug: "databases",
    title: "School of Databases",
    subtitle: "SQL & NoSQL",
    description: "Master relational databases, NoSQL systems, vector databases, data warehousing, and database internals.",
    icon: "database",
    color: "#00ff41",
    order: 6,
    categories: [
      { slug: "sql", title: "SQL Databases", order: 1, modules: [
        { slug: "sql-basics", title: "SQL Fundamentals", order: 1 },
        { slug: "advanced-sql", title: "Advanced SQL", order: 2 },
        { slug: "postgresql", title: "PostgreSQL Deep Dive", order: 3 },
        { slug: "mysql", title: "MySQL", order: 4 },
        { slug: "sqlite", title: "SQLite", order: 5 },
        { slug: "query-optimization", title: "Query Optimization", order: 6 },
      ]},
      { slug: "nosql", title: "NoSQL Databases", order: 2, modules: [
        { slug: "mongodb", title: "MongoDB", order: 1 },
        { slug: "redis", title: "Redis", order: 2 },
        { slug: "cassandra", title: "Apache Cassandra", order: 3 },
        { slug: "neo4j", title: "Neo4j (Graph DB)", order: 4 },
        { slug: "dynamodb", title: "DynamoDB", order: 5 },
        { slug: "firestore", title: "Firestore", order: 6 },
      ]},
      { slug: "vector-databases", title: "Vector Databases", order: 3, modules: [
        { slug: "embeddings", title: "Embeddings & Vector Search", order: 1 },
        { slug: "pgvector", title: "pgvector", order: 2 },
        { slug: "pinecone", title: "Pinecone", order: 3 },
        { slug: "qdrant", title: "Qdrant", order: 4 },
        { slug: "chromadb", title: "ChromaDB", order: 5 },
      ]},
      { slug: "data-warehousing", title: "Data Warehousing", order: 4, modules: [
        { slug: "data-modeling", title: "Data Modeling", order: 1 },
        { slug: "etl-pipelines", title: "ETL Pipelines", order: 2 },
        { slug: "olap", title: "OLAP & Analytics", order: 3 },
        { slug: "snowflake", title: "Snowflake", order: 4 },
        { slug: "bigquery", title: "BigQuery", order: 5 },
      ]},
    ],
  },
  {
    number: 7,
    slug: "cloud-devops",
    title: "School of Cloud & DevOps",
    subtitle: "Infrastructure",
    description: "Learn cloud computing, containerization, CI/CD, infrastructure as code, and DevOps practices.",
    icon: "cloud",
    color: "#00f0ff",
    order: 7,
    categories: [
      { slug: "containers", title: "Containers & Orchestration", order: 1, modules: [
        { slug: "docker", title: "Docker", order: 1 },
        { slug: "kubernetes", title: "Kubernetes", order: 2 },
        { slug: "docker-compose", title: "Docker Compose", order: 3 },
        { slug: "helm", title: "Helm Charts", order: 4 },
        { slug: "service-mesh", title: "Service Mesh", order: 5 },
      ]},
      { slug: "cloud-platforms", title: "Cloud Platforms", order: 2, modules: [
        { slug: "aws", title: "AWS", order: 1 },
        { slug: "azure", title: "Azure", order: 2 },
        { slug: "gcp", title: "GCP", order: 3 },
        { slug: "cloud-comparison", title: "Cloud Comparison", order: 4 },
        { slug: "multi-cloud", title: "Multi-Cloud Strategies", order: 5 },
      ]},
      { slug: "cicd", title: "CI/CD & Automation", order: 3, modules: [
        { slug: "github-actions", title: "GitHub Actions", order: 1 },
        { slug: "gitlab-ci", title: "GitLab CI", order: 2 },
        { slug: "jenkins", title: "Jenkins", order: 3 },
        { slug: "iac", title: "Infrastructure as Code", order: 4 },
        { slug: "terraform", title: "Terraform", order: 5 },
        { slug: "ansible", title: "Ansible", order: 6 },
      ]},
      { slug: "monitoring", title: "Monitoring & Observability", order: 4, modules: [
        { slug: "prometheus", title: "Prometheus", order: 1 },
        { slug: "grafana", title: "Grafana", order: 2 },
        { slug: "logging", title: "Logging (ELK/Loki)", order: 3 },
        { slug: "tracing", title: "Distributed Tracing", order: 4 },
        { slug: "alerting", title: "Alerting & On-Call", order: 5 },
      ]},
    ],
  },
  {
    number: 8,
    slug: "artificial-intelligence",
    title: "School of Artificial Intelligence",
    subtitle: "ML & AI",
    description: "Study machine learning, deep learning, NLP, computer vision, LLMs, AI agents, and MLOps.",
    icon: "brain",
    color: "#ff00aa",
    order: 8,
    categories: [
      { slug: "machine-learning", title: "Machine Learning", order: 1, modules: [
        { slug: "ml-fundamentals", title: "ML Fundamentals", order: 1 },
        { slug: "supervised-learning", title: "Supervised Learning", order: 2 },
        { slug: "unsupervised-learning", title: "Unsupervised Learning", order: 3 },
        { slug: "model-evaluation", title: "Model Evaluation", order: 4 },
        { slug: "feature-engineering", title: "Feature Engineering", order: 5 },
        { slug: "ensemble-methods", title: "Ensemble Methods", order: 6 },
      ]},
      { slug: "deep-learning", title: "Deep Learning", order: 2, modules: [
        { slug: "neural-networks", title: "Neural Networks", order: 1 },
        { slug: "cnn", title: "Convolutional Neural Networks", order: 2 },
        { slug: "rnn-lstm", title: "RNN & LSTM", order: 3 },
        { slug: "transformers", title: "Transformers", order: 4 },
        { slug: "gan", title: "Generative Adversarial Networks", order: 5 },
        { slug: "reinforcement-learning", title: "Reinforcement Learning", order: 6 },
      ]},
      { slug: "llm", title: "Large Language Models", order: 3, modules: [
        { slug: "llm-fundamentals", title: "LLM Fundamentals", order: 1 },
        { slug: "prompt-engineering", title: "Prompt Engineering", order: 2 },
        { slug: "rag", title: "RAG (Retrieval Augmented Generation)", order: 3 },
        { slug: "fine-tuning", title: "Fine-Tuning", order: 4 },
        { slug: "ai-agents", title: "AI Agents", order: 5 },
        { slug: "llm-ops", title: "LLMOps", order: 6 },
      ]},
      { slug: "mlops", title: "MLOps", order: 4, modules: [
        { slug: "ml-pipelines", title: "ML Pipelines", order: 1 },
        { slug: "model-deployment", title: "Model Deployment", order: 2 },
        { slug: "model-monitoring", title: "Model Monitoring", order: 3 },
        { slug: "a-b-testing", title: "A/B Testing", order: 4 },
        { slug: "ml-infrastructure", title: "ML Infrastructure", order: 5 },
      ]},
    ],
  },
  {
    number: 9,
    slug: "cybersecurity",
    title: "School of Cybersecurity",
    subtitle: "Security",
    description: "Learn network security, cryptography, ethical hacking, reverse engineering, malware analysis, and digital forensics.",
    icon: "shield",
    color: "#ff3355",
    order: 9,
    categories: [
      { slug: "network-security", title: "Network Security", order: 1, modules: [
        { slug: "network-fundamentals", title: "Network Fundamentals", order: 1 },
        { slug: "firewalls", title: "Firewalls & IDS/IPS", order: 2 },
        { slug: "vpn", title: "VPN & Tunneling", order: 3 },
        { slug: "wireless-security", title: "Wireless Security", order: 4 },
        { slug: "network-monitoring", title: "Network Monitoring", order: 5 },
      ]},
      { slug: "cryptography", title: "Cryptography", order: 2, modules: [
        { slug: "symmetric-crypto", title: "Symmetric Cryptography", order: 1 },
        { slug: "asymmetric-crypto", title: "Asymmetric Cryptography", order: 2 },
        { slug: "hash-functions", title: "Hash Functions", order: 3 },
        { slug: "digital-signatures", title: "Digital Signatures", order: 4 },
        { slug: "pki", title: "PKI & Certificates", order: 5 },
      ]},
      { slug: "ethical-hacking", title: "Ethical Hacking", order: 3, modules: [
        { slug: "reconnaissance", title: "Reconnaissance", order: 1 },
        { slug: "scanning", title: "Scanning & Enumeration", order: 2 },
        { slug: "exploitation", title: "Exploitation", order: 3 },
        { slug: "post-exploitation", title: "Post-Exploitation", order: 4 },
        { slug: "web-hacking", title: "Web Application Hacking", order: 5 },
      ]},
      { slug: "forensics", title: "Digital Forensics", order: 4, modules: [
        { slug: "forensics-fundamentals", title: "Forensics Fundamentals", order: 1 },
        { slug: "disk-forensics", title: "Disk Forensics", order: 2 },
        { slug: "memory-forensics", title: "Memory Forensics", order: 3 },
        { slug: "network-forensics", title: "Network Forensics", order: 4 },
        { slug: "malware-analysis", title: "Malware Analysis", order: 5 },
      ]},
    ],
  },
  {
    number: 10,
    slug: "embedded-systems",
    title: "School of Embedded Systems",
    subtitle: "Hardware & Firmware",
    description: "Develop embedded systems with microcontrollers, ARM, RISC-V, RTOS, device drivers, and firmware.",
    icon: "chip",
    color: "#ffb000",
    order: 10,
    categories: [
      { slug: "microcontrollers", title: "Microcontrollers", order: 1, modules: [
        { slug: "avr", title: "AVR Microcontrollers", order: 1 },
        { slug: "arm-cortex", title: "ARM Cortex-M", order: 2 },
        { slug: "esp32", title: "ESP32", order: 3 },
        { slug: "raspberry-pi-pico", title: "Raspberry Pi Pico", order: 4 },
        { slug: "stm32", title: "STM32", order: 5 },
      ]},
      { slug: "architectures", title: "Architectures", order: 2, modules: [
        { slug: "arm", title: "ARM Architecture", order: 1 },
        { slug: "risc-v", title: "RISC-V", order: 2 },
        { slug: "x86", title: "x86 Architecture", order: 3 },
      ]},
      { slug: "rtos", title: "Real-Time OS", order: 3, modules: [
        { slug: "rtos-concepts", title: "RTOS Concepts", order: 1 },
        { slug: "freertos", title: "FreeRTOS", order: 2 },
        { slug: "zephyr", title: "Zephyr RTOS", order: 3 },
        { slug: "task-scheduling", title: "Task Scheduling", order: 4 },
        { slug: "interrupts", title: "Interrupts & ISRs", order: 5 },
      ]},
      { slug: "firmware", title: "Firmware Development", order: 4, modules: [
        { slug: "device-drivers", title: "Device Drivers", order: 1 },
        { slug: "firmware-architecture", title: "Firmware Architecture", order: 2 },
        { slug: "bootloaders", title: "Bootloaders", order: 3 },
        { slug: "debugging", title: "Debugging Embedded Systems", order: 4 },
      ]},
    ],
  },
  {
    number: 11,
    slug: "vlsi-chip-design",
    title: "School of VLSI & Chip Design",
    subtitle: "Chip Design",
    description: "Study VLSI design from CMOS fundamentals to ASIC and FPGA development with RTL design in Verilog and VHDL.",
    icon: "circuit",
    color: "#00ff41",
    order: 11,
    categories: [
      { slug: "cmos", title: "CMOS Technology", order: 1, modules: [
        { slug: "cmos-basics", title: "CMOS Fundamentals", order: 1 },
        { slug: "cmos-logic", title: "CMOS Logic Circuits", order: 2 },
        { slug: "cmos-memory", title: "CMOS Memory Design", order: 3 },
        { slug: "layout-design", title: "Layout Design", order: 4 },
      ]},
      { slug: "rtl-design", title: "RTL Design", order: 2, modules: [
        { slug: "verilog", title: "Verilog HDL", order: 1 },
        { slug: "vhdl", title: "VHDL", order: 2 },
        { slug: "systemverilog", title: "SystemVerilog", order: 3 },
        { slug: "fsm-design", title: "FSM Design", order: 4 },
        { slug: "synthesis", title: "Logic Synthesis", order: 5 },
      ]},
      { slug: "asic-fpga", title: "ASIC & FPGA", order: 3, modules: [
        { slug: "fpga-architecture", title: "FPGA Architecture", order: 1 },
        { slug: "fpga-design", title: "FPGA Design Flow", order: 2 },
        { slug: "asic-flow", title: "ASIC Design Flow", order: 3 },
        { slug: "timing-analysis", title: "Timing Analysis", order: 4 },
        { slug: "verification", title: "Verification", order: 5 },
      ]},
    ],
  },
  {
    number: 12,
    slug: "robotics-iot",
    title: "School of Robotics & IoT",
    subtitle: "Robotics & IoT",
    description: "Build robots and IoT systems with ROS, sensors, actuators, PLCs, MQTT, and LoRaWAN.",
    icon: "bot",
    color: "#00f0ff",
    order: 12,
    categories: [
      { slug: "robotics", title: "Robotics", order: 1, modules: [
        { slug: "ros", title: "ROS (Robot Operating System)", order: 1 },
        { slug: "sensors", title: "Sensors & Perception", order: 2 },
        { slug: "actuators", title: "Actuators & Control", order: 3 },
        { slug: "kinematics", title: "Kinematics", order: 4 },
        { slug: "robot-control", title: "Robot Control Systems", order: 5 },
      ]},
      { slug: "iot", title: "Internet of Things", order: 2, modules: [
        { slug: "iot-architecture", title: "IoT Architecture", order: 1 },
        { slug: "mqtt", title: "MQTT Protocol", order: 2 },
        { slug: "lorawan", title: "LoRaWAN", order: 3 },
        { slug: "iot-security", title: "IoT Security", order: 4 },
        { slug: "edge-computing", title: "Edge Computing", order: 5 },
      ]},
      { slug: "plc-scada", title: "PLC & SCADA", order: 3, modules: [
        { slug: "plc-basics", title: "PLC Fundamentals", order: 1 },
        { slug: "ladder-logic", title: "Ladder Logic", order: 2 },
        { slug: "scada", title: "SCADA Systems", order: 3 },
        { slug: "industrial-automation", title: "Industrial Automation", order: 4 },
      ]},
    ],
  },
  {
    number: 13,
    slug: "computer-graphics",
    title: "School of Computer Graphics",
    subtitle: "Graphics & Rendering",
    description: "Master computer graphics with OpenGL, Vulkan, DirectX, WebGPU, ray tracing, and GPU programming.",
    icon: "image",
    color: "#ff00aa",
    order: 13,
    categories: [
      { slug: "graphics-fundamentals", title: "Graphics Fundamentals", order: 1, modules: [
        { slug: "rendering-pipeline", title: "Rendering Pipeline", order: 1 },
        { slug: "transformations", title: "Transformations & Matrices", order: 2 },
        { slug: "lighting", title: "Lighting & Shading", order: 3 },
        { slug: "texturing", title: "Texturing", order: 4 },
        { slug: "shaders", title: "Shaders (GLSL/HLSL)", order: 5 },
      ]},
      { slug: "graphics-apis", title: "Graphics APIs", order: 2, modules: [
        { slug: "opengl", title: "OpenGL", order: 1 },
        { slug: "vulkan", title: "Vulkan", order: 2 },
        { slug: "directx", title: "DirectX 12", order: 3 },
        { slug: "webgpu", title: "WebGPU", order: 4 },
        { slug: "metal", title: "Metal", order: 5 },
      ]},
      { slug: "advanced-rendering", title: "Advanced Rendering", order: 3, modules: [
        { slug: "ray-tracing", title: "Ray Tracing", order: 1 },
        { slug: "global-illumination", title: "Global Illumination", order: 2 },
        { slug: "gpu-computing", title: "GPU Computing (CUDA)", order: 3 },
        { slug: "procedural-generation", title: "Procedural Generation", order: 4 },
        { slug: "post-processing", title: "Post-Processing Effects", order: 5 },
      ]},
    ],
  },
  {
    number: 14,
    slug: "game-development",
    title: "School of Game Development",
    subtitle: "Game Dev",
    description: "Create games with Unity, Unreal Engine, and Godot. Learn game physics, multiplayer networking, and game AI.",
    icon: "gamepad",
    color: "#ffb000",
    order: 14,
    categories: [
      { slug: "game-engines", title: "Game Engines", order: 1, modules: [
        { slug: "unity", title: "Unity", order: 1 },
        { slug: "unreal", title: "Unreal Engine", order: 2 },
        { slug: "godot", title: "Godot", order: 3 },
        { slug: "custom-engines", title: "Custom Game Engines", order: 4 },
      ]},
      { slug: "game-systems", title: "Game Systems", order: 2, modules: [
        { slug: "physics", title: "Game Physics", order: 1 },
        { slug: "multiplayer", title: "Multiplayer Networking", order: 2 },
        { slug: "game-ai", title: "Game AI", order: 3 },
        { slug: "audio", title: "Game Audio", order: 4 },
        { slug: "input-systems", title: "Input Systems", order: 5 },
      ]},
      { slug: "game-design", title: "Game Design", order: 3, modules: [
        { slug: "game-design-principles", title: "Game Design Principles", order: 1 },
        { slug: "level-design", title: "Level Design", order: 2 },
        { slug: "ui-design", title: "Game UI/UX", order: 3 },
        { slug: "game-testing", title: "Game Testing", order: 4 },
        { slug: "publishing", title: "Publishing & Monetization", order: 5 },
      ]},
    ],
  },
  {
    number: 15,
    slug: "blockchain-web3",
    title: "School of Blockchain & Web3",
    subtitle: "Blockchain",
    description: "Build decentralized applications with Ethereum, Solidity, smart contracts, DeFi, and Layer 2 solutions.",
    icon: "link",
    color: "#00f0ff",
    order: 15,
    categories: [
      { slug: "blockchain-fundamentals", title: "Blockchain Fundamentals", order: 1, modules: [
        { slug: "blockchain-basics", title: "Blockchain Basics", order: 1 },
        { slug: "consensus", title: "Consensus Mechanisms", order: 2 },
        { slug: "cryptography-in-blockchain", title: "Cryptography in Blockchain", order: 3 },
        { slug: "bitcoin", title: "Bitcoin Protocol", order: 4 },
      ]},
      { slug: "ethereum", title: "Ethereum & Smart Contracts", order: 2, modules: [
        { slug: "ethereum-basics", title: "Ethereum Fundamentals", order: 1 },
        { slug: "solidity", title: "Solidity", order: 2 },
        { slug: "smart-contracts", title: "Smart Contract Development", order: 3 },
        { slug: "web3-js", title: "Web3.js & Ethers.js", order: 4 },
        { slug: "hardhat", title: "Hardhat & Foundry", order: 5 },
      ]},
      { slug: "defi", title: "DeFi & Layer 2", order: 3, modules: [
        { slug: "defi-basics", title: "DeFi Fundamentals", order: 1 },
        { slug: "amm", title: "Automated Market Makers", order: 2 },
        { slug: "layer2", title: "Layer 2 Solutions", order: 3 },
        { slug: "nft", title: "NFT Standards & Marketplaces", order: 4 },
        { slug: "dao", title: "DAOs", order: 5 },
      ]},
    ],
  },
  {
    number: 16,
    slug: "cs-core",
    title: "School of Computer Science Core",
    subtitle: "Core CS",
    description: "Master the core theoretical foundations of computer science including operating systems, networks, and theory of computation.",
    icon: "book",
    color: "#ff3355",
    order: 16,
    categories: [
      { slug: "operating-systems", title: "Operating Systems", order: 1, modules: [
        { slug: "os-fundamentals", title: "OS Fundamentals", order: 1 },
        { slug: "process-management", title: "Process Management", order: 2 },
        { slug: "memory-management", title: "Memory Management", order: 3 },
        { slug: "file-systems", title: "File Systems", order: 4 },
        { slug: "io-systems", title: "I/O Systems", order: 5 },
        { slug: "virtualization", title: "Virtualization", order: 6 },
      ]},
      { slug: "computer-networks", title: "Computer Networks", order: 2, modules: [
        { slug: "network-layers", title: "Network Layers (OSI/TCP)", order: 1 },
        { slug: "application-layer", title: "Application Layer", order: 2 },
        { slug: "transport-layer", title: "Transport Layer", order: 3 },
        { slug: "network-layer", title: "Network Layer", order: 4 },
        { slug: "link-layer", title: "Link Layer", order: 5 },
        { slug: "network-security", title: "Network Security", order: 6 },
      ]},
      { slug: "theory-of-computation", title: "Theory of Computation", order: 3, modules: [
        { slug: "automata", title: "Automata Theory", order: 1 },
        { slug: "formal-languages", title: "Formal Languages", order: 2 },
        { slug: "turing-machines", title: "Turing Machines", order: 3 },
        { slug: "computability", title: "Computability Theory", order: 4 },
        { slug: "complexity", title: "Complexity Theory (P vs NP)", order: 5 },
      ]},
      { slug: "distributed-systems", title: "Distributed Systems", order: 4, modules: [
        { slug: "distributed-architectures", title: "Distributed Architectures", order: 1 },
        { slug: "consistency", title: "Consistency & Replication", order: 2 },
        { slug: "distributed-storage", title: "Distributed Storage", order: 3 },
        { slug: "distributed-computing", title: "Distributed Computing", order: 4 },
        { slug: "distributed-consensus", title: "Distributed Consensus", order: 5 },
      ]},
    ],
  },
  {
    number: 17,
    slug: "software-engineering",
    title: "School of Software Engineering",
    subtitle: "Software Engineering",
    description: "Learn professional software engineering practices including clean code, design patterns, system design, testing, and architecture.",
    icon: "building",
    color: "#00ff41",
    order: 17,
    categories: [
      { slug: "clean-code", title: "Clean Code", order: 1, modules: [
        { slug: "naming", title: "Meaningful Names", order: 1 },
        { slug: "functions", title: "Clean Functions", order: 2 },
        { slug: "comments", title: "Comments & Documentation", order: 3 },
        { slug: "formatting", title: "Code Formatting", order: 4 },
        { slug: "error-handling", title: "Error Handling", order: 5 },
        { slug: "refactoring", title: "Refactoring", order: 6 },
      ]},
      { slug: "design-patterns", title: "Design Patterns", order: 2, modules: [
        { slug: "creational", title: "Creational Patterns", order: 1 },
        { slug: "structural", title: "Structural Patterns", order: 2 },
        { slug: "behavioral", title: "Behavioral Patterns", order: 3 },
        { slug: "architectural", title: "Architectural Patterns", order: 4 },
        { slug: "idioms", title: "Language-Specific Idioms", order: 5 },
      ]},
      { slug: "system-design", title: "System Design", order: 3, modules: [
        { slug: "design-fundamentals", title: "Design Fundamentals", order: 1 },
        { slug: "scalability", title: "Scalability", order: 2 },
        { slug: "microservices", title: "Microservices", order: 3 },
        { slug: "database-design", title: "Database Design", order: 4 },
        { slug: "api-design", title: "API Design", order: 5 },
        { slug: "case-studies", title: "System Design Case Studies", order: 6 },
      ]},
      { slug: "testing", title: "Testing", order: 4, modules: [
        { slug: "unit-testing", title: "Unit Testing", order: 1 },
        { slug: "integration-testing", title: "Integration Testing", order: 2 },
        { slug: "e2e-testing", title: "End-to-End Testing", order: 3 },
        { slug: "tdd", title: "Test-Driven Development", order: 4 },
        { slug: "ci-testing", title: "CI/CD Testing", order: 5 },
      ]},
    ],
  },
  {
    number: 18,
    slug: "career-development",
    title: "School of Career Development",
    subtitle: "Career Growth",
    description: "Build your career with resume writing, portfolio creation, open source contributions, freelancing, startups, and interview preparation.",
    icon: "briefcase",
    color: "#ffb000",
    order: 18,
    categories: [
      { slug: "resume-portfolio", title: "Resume & Portfolio", order: 1, modules: [
        { slug: "resume-writing", title: "Resume Writing", order: 1 },
        { slug: "portfolio-building", title: "Portfolio Building", order: 2 },
        { slug: "github-profile", title: "GitHub Profile", order: 3 },
        { slug: "linkedin", title: "LinkedIn Optimization", order: 4 },
        { slug: "personal-branding", title: "Personal Branding", order: 5 },
      ]},
      { slug: "job-search", title: "Job Search", order: 2, modules: [
        { slug: "job-hunting", title: "Job Hunting Strategies", order: 1 },
        { slug: "networking", title: "Networking", order: 2 },
        { slug: "cover-letters", title: "Cover Letters", order: 3 },
        { slug: "salary-negotiation", title: "Salary Negotiation", order: 4 },
        { slug: "remote-work", title: "Remote Work", order: 5 },
      ]},
      { slug: "interview-prep", title: "Interview Preparation", order: 3, modules: [
        { slug: "coding-interviews", title: "Coding Interviews", order: 1 },
        { slug: "system-design-interviews", title: "System Design Interviews", order: 2 },
        { slug: "behavioral-interviews", title: "Behavioral Interviews", order: 3 },
        { slug: "mock-interviews", title: "Mock Interviews", order: 4 },
        { slug: "tech-screen", title: "Technical Screens", order: 5 },
      ]},
      { slug: "career-paths", title: "Career Paths", order: 4, modules: [
        { slug: "open-source", title: "Open Source Contributions", order: 1 },
        { slug: "freelancing", title: "Freelancing", order: 2 },
        { slug: "startups", title: "Startups", order: 3 },
        { slug: "tech-lead", title: "Tech Lead & Management", order: 4 },
        { slug: "continuous-learning", title: "Continuous Learning", order: 5 },
      ]},
    ],
  },
  {
    number: 19,
    slug: "developer-tools",
    title: "School of Developer Tools",
    subtitle: "Tools & Workflow",
    description: "Master essential developer tools including IDEs, editors, version control, build tools, package managers, and productivity tools.",
    icon: "wrench",
    color: "#00aaff",
    order: 19,
    categories: [
      { slug: "editors-ides", title: "Editors & IDEs", order: 1, modules: [
        { slug: "vscode", title: "VS Code", order: 1 },
        { slug: "vim", title: "Vim", order: 2 },
        { slug: "intellij", title: "IntelliJ IDEA", order: 3 },
        { slug: "emacs", title: "Emacs", order: 4 },
        { slug: "terminal-emulators", title: "Terminal Emulators", order: 5 },
      ]},
      { slug: "version-control", title: "Version Control", order: 2, modules: [
        { slug: "git-basics", title: "Git Fundamentals", order: 1 },
        { slug: "advanced-git", title: "Advanced Git", order: 2 },
        { slug: "github", title: "GitHub Workflows", order: 3 },
        { slug: "gitops", title: "GitOps", order: 4 },
      ]},
      { slug: "build-tools", title: "Build Tools & Package Managers", order: 3, modules: [
        { slug: "npm-yarn", title: "npm & Yarn", order: 1 },
        { slug: "webpack-vite", title: "Webpack & Vite", order: 2 },
        { slug: "esbuild", title: "esbuild", order: 3 },
        { slug: "cargo", title: "Cargo (Rust)", order: 4 },
        { slug: "gradle-maven", title: "Gradle & Maven", order: 5 },
        { slug: "make-cmake", title: "Make & CMake", order: 6 },
      ]},
      { slug: "productivity", title: "Productivity", order: 4, modules: [
        { slug: "terminal-tools", title: "Terminal Productivity", order: 1 },
        { slug: "docker-tools", title: "Docker for Development", order: 2 },
        { slug: "api-clients", title: "API Clients (Postman, curl)", order: 3 },
        { slug: "note-taking", title: "Note Taking & Knowledge Mgmt", order: 4 },
        { slug: "automation", title: "Development Automation", order: 5 },
      ]},
    ],
  },
  {
    number: 20,
    slug: "emerging-technologies",
    title: "School of Emerging Technologies",
    subtitle: "Future Tech",
    description: "Explore cutting-edge technologies including quantum computing, edge computing, AR/VR, mixed reality, digital twins, and neuromorphic computing.",
    icon: "sparkles",
    color: "#ff00aa",
    order: 20,
    categories: [
      { slug: "quantum-computing", title: "Quantum Computing", order: 1, modules: [
        { slug: "quantum-basics", title: "Quantum Computing Basics", order: 1 },
        { slug: "quantum-gates", title: "Quantum Gates & Circuits", order: 2 },
        { slug: "quantum-algorithms", title: "Quantum Algorithms", order: 3 },
        { slug: "qiskit", title: "Qiskit Framework", order: 4 },
        { slug: "quantum-hardware", title: "Quantum Hardware", order: 5 },
      ]},
      { slug: "ar-vr", title: "AR/VR & Mixed Reality", order: 2, modules: [
        { slug: "ar-basics", title: "AR Fundamentals", order: 1 },
        { slug: "vr-basics", title: "VR Fundamentals", order: 2 },
        { slug: "mixed-reality", title: "Mixed Reality", order: 3 },
        { slug: "spatial-computing", title: "Spatial Computing", order: 4 },
        { slug: "ar-frameworks", title: "AR Frameworks (ARKit, ARCore)", order: 5 },
      ]},
      { slug: "edge-computing", title: "Edge Computing", order: 3, modules: [
        { slug: "edge-basics", title: "Edge Computing Fundamentals", order: 1 },
        { slug: "edge-architecture", title: "Edge Architecture", order: 2 },
        { slug: "edge-ml", title: "Edge ML", order: 3 },
        { slug: "edge-devices", title: "Edge Devices", order: 4 },
      ]},
      { slug: "future-tech", title: "Future Technologies", order: 4, modules: [
        { slug: "digital-twins", title: "Digital Twins", order: 1 },
        { slug: "neuromorphic", title: "Neuromorphic Computing", order: 2 },
        { slug: "bio-computing", title: "Bio-Computing", order: 3 },
        { slug: "photonics", title: "Photonics Computing", order: 4 },
        { slug: "web4", title: "Web4 & Decentralized Internet", order: 5 },
      ]},
    ],
  },
]

async function main() {
  console.log("Seeding LupaLearn database...")

  for (const schoolData of SCHOOLS) {
    const { categories, ...volumeData } = schoolData

    const volume = await prisma.volume.upsert({
      where: { number: volumeData.number },
      update: volumeData,
      create: volumeData,
    })

    for (const catData of categories) {
      const { modules, ...categoryData } = catData

      const category = await prisma.category.upsert({
        where: { id: `${volume.id}-${catData.slug}` },
        update: { ...categoryData, volumeId: volume.id },
        create: { ...categoryData, volumeId: volume.id, id: `${volume.id}-${catData.slug}` },
      })

      for (const modData of modules) {
        await prisma.module.upsert({
          where: { id: `${category.id}-${modData.slug}` },
          update: { ...modData, categoryId: category.id },
          create: { ...modData, categoryId: category.id, id: `${category.id}-${modData.slug}` },
        })
      }
    }
  }

  console.log("✅ All 20 schools seeded successfully!")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
