import type { editor } from "monaco-editor"

export const editorTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "606060", fontStyle: "italic" },
    { token: "keyword", foreground: "00ff41" },
    { token: "keyword.control", foreground: "00ff41" },
    { token: "string", foreground: "ffb000" },
    { token: "string.quoted", foreground: "ffb000" },
    { token: "number", foreground: "00f0ff" },
    { token: "type", foreground: "00aaff" },
    { token: "type.identifier", foreground: "00aaff" },
    { token: "function", foreground: "ff00aa" },
    { token: "variable", foreground: "c0c0c0" },
    { token: "variable.parameter", foreground: "c0c0c0" },
    { token: "operator", foreground: "00ff41" },
    { token: "delimiter", foreground: "606060" },
    { token: "tag", foreground: "00f0ff" },
    { token: "attribute.name", foreground: "ffb000" },
    { token: "attribute.value", foreground: "00ff41" },
    { token: "metatag", foreground: "00f0ff" },
  ],
  colors: {
    "editor.background": "#0a0a0a",
    "editor.foreground": "#c0c0c0",
    "editorCursor.foreground": "#00ff41",
    "editorLineNumber.foreground": "#606060",
    "editorLineNumber.activeForeground": "#c0c0c0",
    "editor.selectionBackground": "#00ff4133",
    "editor.inactiveSelectionBackground": "#00ff4120",
    "editor.selectionHighlightBackground": "#00ff4110",
    "editor.wordHighlightBackground": "#00ff4110",
    "editor.wordHighlightStrongBackground": "#00ff4120",
    "editorBracketMatch.background": "#00ff4120",
    "editorBracketMatch.border": "#00ff41",
    "editorWidget.background": "#121212",
    "editorWidget.border": "#1e1e1e",
    "input.background": "#1a1a1a",
    "input.border": "#1e1e1e",
    "list.activeSelectionBackground": "#1a1a1a",
    "list.hoverBackground": "#121212",
    "list.highlightForeground": "#00ff41",
    "scrollbarSlider.background": "#1e1e1e",
    "scrollbarSlider.hoverBackground": "#2a2a2a",
    "scrollbarSlider.activeBackground": "#3a3a3a",
  },
}
